package net.neoforged.camelot.api.config.type;

import java.util.List;
import java.util.function.Function;
import java.util.function.UnaryOperator;

// This file is autogenerated. DO NOT MODIFY IT MANUALLY
public interface ObjectOptionBuilders {
    /**
     * A builder for composite objects with 1 fields.
     */
    interface Builder1<TGT, OBJ, A> {
        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param optionConfigurator   a unary operator used to configure the field option
         * @param <NEW>                the type of the field to add
         * @param <FROM>               the type of the option factory. This can be different to facilitate eventual mapping
         * @param <FB>                 the type of the field's builder
         * @return a new builder with the added field
         */
        <NEW, FROM, FB extends OptionBuilder<TGT, FROM, FB>> Builder2<TGT, OBJ, A, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, FROM, FB> fieldFactory, Function<FB, ? extends OptionBuilder<TGT, NEW, ?>> optionConfigurator);

        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param displayName          the display name of the field
         * @param description          the description of the field
         * @param <NEW>                the type of the field to add
         * @return a new builder with the added field
         */
        <NEW> Builder2<TGT, OBJ, A, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, NEW, ?> fieldFactory, String displayName, String description);

        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param displayName          the display name of the field
         * @param description          the description of the field
         * @param defaultValue         the default value of the field
         * @param <NEW>                the type of the field to add
         * @return a new builder with the added field
         */
        <NEW> Builder2<TGT, OBJ, A, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, NEW, ?> fieldFactory, String displayName, String description, NEW defaultValue);
        /**
         * {@return an option builder factory for object options of this type}
         * The fields will be turned into the object using the given {@code constructor}.
         *
         * @param constructor the function used to construct the object from the fields
         */
        OptionBuilderFactory<TGT, OBJ, OptionBuilder.Composite<TGT, OBJ>> construct(Constructor1<A, OBJ> constructor);
    }

    /**
     * A builder for composite objects with 2 fields.
     */
    interface Builder2<TGT, OBJ, A, B> {
        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param optionConfigurator   a unary operator used to configure the field option
         * @param <NEW>                the type of the field to add
         * @param <FROM>               the type of the option factory. This can be different to facilitate eventual mapping
         * @param <FB>                 the type of the field's builder
         * @return a new builder with the added field
         */
        <NEW, FROM, FB extends OptionBuilder<TGT, FROM, FB>> Builder3<TGT, OBJ, A, B, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, FROM, FB> fieldFactory, Function<FB, ? extends OptionBuilder<TGT, NEW, ?>> optionConfigurator);

        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param displayName          the display name of the field
         * @param description          the description of the field
         * @param <NEW>                the type of the field to add
         * @return a new builder with the added field
         */
        <NEW> Builder3<TGT, OBJ, A, B, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, NEW, ?> fieldFactory, String displayName, String description);

        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param displayName          the display name of the field
         * @param description          the description of the field
         * @param defaultValue         the default value of the field
         * @param <NEW>                the type of the field to add
         * @return a new builder with the added field
         */
        <NEW> Builder3<TGT, OBJ, A, B, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, NEW, ?> fieldFactory, String displayName, String description, NEW defaultValue);
        /**
         * {@return an option builder factory for object options of this type}
         * The fields will be turned into the object using the given {@code constructor}.
         *
         * @param constructor the function used to construct the object from the fields
         */
        OptionBuilderFactory<TGT, OBJ, OptionBuilder.Composite<TGT, OBJ>> construct(Constructor2<A, B, OBJ> constructor);
    }

    /**
     * A builder for composite objects with 3 fields.
     */
    interface Builder3<TGT, OBJ, A, B, C> {
        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param optionConfigurator   a unary operator used to configure the field option
         * @param <NEW>                the type of the field to add
         * @param <FROM>               the type of the option factory. This can be different to facilitate eventual mapping
         * @param <FB>                 the type of the field's builder
         * @return a new builder with the added field
         */
        <NEW, FROM, FB extends OptionBuilder<TGT, FROM, FB>> Builder4<TGT, OBJ, A, B, C, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, FROM, FB> fieldFactory, Function<FB, ? extends OptionBuilder<TGT, NEW, ?>> optionConfigurator);

        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param displayName          the display name of the field
         * @param description          the description of the field
         * @param <NEW>                the type of the field to add
         * @return a new builder with the added field
         */
        <NEW> Builder4<TGT, OBJ, A, B, C, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, NEW, ?> fieldFactory, String displayName, String description);

        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param displayName          the display name of the field
         * @param description          the description of the field
         * @param defaultValue         the default value of the field
         * @param <NEW>                the type of the field to add
         * @return a new builder with the added field
         */
        <NEW> Builder4<TGT, OBJ, A, B, C, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, NEW, ?> fieldFactory, String displayName, String description, NEW defaultValue);
        /**
         * {@return an option builder factory for object options of this type}
         * The fields will be turned into the object using the given {@code constructor}.
         *
         * @param constructor the function used to construct the object from the fields
         */
        OptionBuilderFactory<TGT, OBJ, OptionBuilder.Composite<TGT, OBJ>> construct(Constructor3<A, B, C, OBJ> constructor);
    }

    /**
     * A builder for composite objects with 4 fields.
     */
    interface Builder4<TGT, OBJ, A, B, C, D> {
        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param optionConfigurator   a unary operator used to configure the field option
         * @param <NEW>                the type of the field to add
         * @param <FROM>               the type of the option factory. This can be different to facilitate eventual mapping
         * @param <FB>                 the type of the field's builder
         * @return a new builder with the added field
         */
        <NEW, FROM, FB extends OptionBuilder<TGT, FROM, FB>> Builder5<TGT, OBJ, A, B, C, D, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, FROM, FB> fieldFactory, Function<FB, ? extends OptionBuilder<TGT, NEW, ?>> optionConfigurator);

        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param displayName          the display name of the field
         * @param description          the description of the field
         * @param <NEW>                the type of the field to add
         * @return a new builder with the added field
         */
        <NEW> Builder5<TGT, OBJ, A, B, C, D, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, NEW, ?> fieldFactory, String displayName, String description);

        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param displayName          the display name of the field
         * @param description          the description of the field
         * @param defaultValue         the default value of the field
         * @param <NEW>                the type of the field to add
         * @return a new builder with the added field
         */
        <NEW> Builder5<TGT, OBJ, A, B, C, D, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, NEW, ?> fieldFactory, String displayName, String description, NEW defaultValue);
        /**
         * {@return an option builder factory for object options of this type}
         * The fields will be turned into the object using the given {@code constructor}.
         *
         * @param constructor the function used to construct the object from the fields
         */
        OptionBuilderFactory<TGT, OBJ, OptionBuilder.Composite<TGT, OBJ>> construct(Constructor4<A, B, C, D, OBJ> constructor);
    }

    /**
     * A builder for composite objects with 5 fields.
     */
    interface Builder5<TGT, OBJ, A, B, C, D, E> {
        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param optionConfigurator   a unary operator used to configure the field option
         * @param <NEW>                the type of the field to add
         * @param <FROM>               the type of the option factory. This can be different to facilitate eventual mapping
         * @param <FB>                 the type of the field's builder
         * @return a new builder with the added field
         */
        <NEW, FROM, FB extends OptionBuilder<TGT, FROM, FB>> Builder6<TGT, OBJ, A, B, C, D, E, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, FROM, FB> fieldFactory, Function<FB, ? extends OptionBuilder<TGT, NEW, ?>> optionConfigurator);

        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param displayName          the display name of the field
         * @param description          the description of the field
         * @param <NEW>                the type of the field to add
         * @return a new builder with the added field
         */
        <NEW> Builder6<TGT, OBJ, A, B, C, D, E, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, NEW, ?> fieldFactory, String displayName, String description);

        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param displayName          the display name of the field
         * @param description          the description of the field
         * @param defaultValue         the default value of the field
         * @param <NEW>                the type of the field to add
         * @return a new builder with the added field
         */
        <NEW> Builder6<TGT, OBJ, A, B, C, D, E, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, NEW, ?> fieldFactory, String displayName, String description, NEW defaultValue);
        /**
         * {@return an option builder factory for object options of this type}
         * The fields will be turned into the object using the given {@code constructor}.
         *
         * @param constructor the function used to construct the object from the fields
         */
        OptionBuilderFactory<TGT, OBJ, OptionBuilder.Composite<TGT, OBJ>> construct(Constructor5<A, B, C, D, E, OBJ> constructor);
    }

    /**
     * A builder for composite objects with 6 fields.
     */
    interface Builder6<TGT, OBJ, A, B, C, D, E, F> {
        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param optionConfigurator   a unary operator used to configure the field option
         * @param <NEW>                the type of the field to add
         * @param <FROM>               the type of the option factory. This can be different to facilitate eventual mapping
         * @param <FB>                 the type of the field's builder
         * @return a new builder with the added field
         */
        <NEW, FROM, FB extends OptionBuilder<TGT, FROM, FB>> Builder7<TGT, OBJ, A, B, C, D, E, F, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, FROM, FB> fieldFactory, Function<FB, ? extends OptionBuilder<TGT, NEW, ?>> optionConfigurator);

        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param displayName          the display name of the field
         * @param description          the description of the field
         * @param <NEW>                the type of the field to add
         * @return a new builder with the added field
         */
        <NEW> Builder7<TGT, OBJ, A, B, C, D, E, F, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, NEW, ?> fieldFactory, String displayName, String description);

        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param displayName          the display name of the field
         * @param description          the description of the field
         * @param defaultValue         the default value of the field
         * @param <NEW>                the type of the field to add
         * @return a new builder with the added field
         */
        <NEW> Builder7<TGT, OBJ, A, B, C, D, E, F, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, NEW, ?> fieldFactory, String displayName, String description, NEW defaultValue);
        /**
         * {@return an option builder factory for object options of this type}
         * The fields will be turned into the object using the given {@code constructor}.
         *
         * @param constructor the function used to construct the object from the fields
         */
        OptionBuilderFactory<TGT, OBJ, OptionBuilder.Composite<TGT, OBJ>> construct(Constructor6<A, B, C, D, E, F, OBJ> constructor);
    }

    /**
     * A builder for composite objects with 7 fields.
     */
    interface Builder7<TGT, OBJ, A, B, C, D, E, F, G> {
        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param optionConfigurator   a unary operator used to configure the field option
         * @param <NEW>                the type of the field to add
         * @param <FROM>               the type of the option factory. This can be different to facilitate eventual mapping
         * @param <FB>                 the type of the field's builder
         * @return a new builder with the added field
         */
        <NEW, FROM, FB extends OptionBuilder<TGT, FROM, FB>> Builder8<TGT, OBJ, A, B, C, D, E, F, G, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, FROM, FB> fieldFactory, Function<FB, ? extends OptionBuilder<TGT, NEW, ?>> optionConfigurator);

        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param displayName          the display name of the field
         * @param description          the description of the field
         * @param <NEW>                the type of the field to add
         * @return a new builder with the added field
         */
        <NEW> Builder8<TGT, OBJ, A, B, C, D, E, F, G, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, NEW, ?> fieldFactory, String displayName, String description);

        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param displayName          the display name of the field
         * @param description          the description of the field
         * @param defaultValue         the default value of the field
         * @param <NEW>                the type of the field to add
         * @return a new builder with the added field
         */
        <NEW> Builder8<TGT, OBJ, A, B, C, D, E, F, G, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, NEW, ?> fieldFactory, String displayName, String description, NEW defaultValue);
        /**
         * {@return an option builder factory for object options of this type}
         * The fields will be turned into the object using the given {@code constructor}.
         *
         * @param constructor the function used to construct the object from the fields
         */
        OptionBuilderFactory<TGT, OBJ, OptionBuilder.Composite<TGT, OBJ>> construct(Constructor7<A, B, C, D, E, F, G, OBJ> constructor);
    }

    /**
     * A builder for composite objects with 8 fields.
     */
    interface Builder8<TGT, OBJ, A, B, C, D, E, F, G, H> {
        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param optionConfigurator   a unary operator used to configure the field option
         * @param <NEW>                the type of the field to add
         * @param <FROM>               the type of the option factory. This can be different to facilitate eventual mapping
         * @param <FB>                 the type of the field's builder
         * @return a new builder with the added field
         */
        <NEW, FROM, FB extends OptionBuilder<TGT, FROM, FB>> Builder9<TGT, OBJ, A, B, C, D, E, F, G, H, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, FROM, FB> fieldFactory, Function<FB, ? extends OptionBuilder<TGT, NEW, ?>> optionConfigurator);

        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param displayName          the display name of the field
         * @param description          the description of the field
         * @param <NEW>                the type of the field to add
         * @return a new builder with the added field
         */
        <NEW> Builder9<TGT, OBJ, A, B, C, D, E, F, G, H, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, NEW, ?> fieldFactory, String displayName, String description);

        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param displayName          the display name of the field
         * @param description          the description of the field
         * @param defaultValue         the default value of the field
         * @param <NEW>                the type of the field to add
         * @return a new builder with the added field
         */
        <NEW> Builder9<TGT, OBJ, A, B, C, D, E, F, G, H, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, NEW, ?> fieldFactory, String displayName, String description, NEW defaultValue);
        /**
         * {@return an option builder factory for object options of this type}
         * The fields will be turned into the object using the given {@code constructor}.
         *
         * @param constructor the function used to construct the object from the fields
         */
        OptionBuilderFactory<TGT, OBJ, OptionBuilder.Composite<TGT, OBJ>> construct(Constructor8<A, B, C, D, E, F, G, H, OBJ> constructor);
    }

    /**
     * A builder for composite objects with 9 fields.
     */
    interface Builder9<TGT, OBJ, A, B, C, D, E, F, G, H, I> {
        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param optionConfigurator   a unary operator used to configure the field option
         * @param <NEW>                the type of the field to add
         * @param <FROM>               the type of the option factory. This can be different to facilitate eventual mapping
         * @param <FB>                 the type of the field's builder
         * @return a new builder with the added field
         */
        <NEW, FROM, FB extends OptionBuilder<TGT, FROM, FB>> Builder10<TGT, OBJ, A, B, C, D, E, F, G, H, I, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, FROM, FB> fieldFactory, Function<FB, ? extends OptionBuilder<TGT, NEW, ?>> optionConfigurator);

        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param displayName          the display name of the field
         * @param description          the description of the field
         * @param <NEW>                the type of the field to add
         * @return a new builder with the added field
         */
        <NEW> Builder10<TGT, OBJ, A, B, C, D, E, F, G, H, I, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, NEW, ?> fieldFactory, String displayName, String description);

        /**
         * Add a field to this composite object.
         *
         * @param id                   the id of the field
         * @param extractor            the function that extracts the field value from the object
         * @param fieldFactory         the option factory to create the field's option
         * @param displayName          the display name of the field
         * @param description          the description of the field
         * @param defaultValue         the default value of the field
         * @param <NEW>                the type of the field to add
         * @return a new builder with the added field
         */
        <NEW> Builder10<TGT, OBJ, A, B, C, D, E, F, G, H, I, NEW> field(String id, Function<OBJ, NEW> extractor, OptionBuilderFactory<TGT, NEW, ?> fieldFactory, String displayName, String description, NEW defaultValue);
        /**
         * {@return an option builder factory for object options of this type}
         * The fields will be turned into the object using the given {@code constructor}.
         *
         * @param constructor the function used to construct the object from the fields
         */
        OptionBuilderFactory<TGT, OBJ, OptionBuilder.Composite<TGT, OBJ>> construct(Constructor9<A, B, C, D, E, F, G, H, I, OBJ> constructor);
    }

    /**
     * A builder for composite objects with 10 fields.
     */
    interface Builder10<TGT, OBJ, A, B, C, D, E, F, G, H, I, J> {
        
        /**
         * {@return an option builder factory for object options of this type}
         * The fields will be turned into the object using the given {@code constructor}.
         *
         * @param constructor the function used to construct the object from the fields
         */
        OptionBuilderFactory<TGT, OBJ, OptionBuilder.Composite<TGT, OBJ>> construct(Constructor10<A, B, C, D, E, F, G, H, I, J, OBJ> constructor);
    }

    /**
     * A constructor function with 1 argument.
     */
    interface Constructor1<A, RESULT> {
        /**
         * {@return the object constructed with the given arguments}
         */
        RESULT create(A arg0);

        /**
         * {@return the object constructed with the given arguments}
         *
         * @param arguments the arguments as an ordered list
         */
        @SuppressWarnings("unchecked")
        default RESULT createFromList(List<Object> arguments) {
            return create((A) arguments.get(0));
        }
    }
    /**
     * A constructor function with 2 arguments.
     */
    interface Constructor2<A, B, RESULT> {
        /**
         * {@return the object constructed with the given arguments}
         */
        RESULT create(A arg0, B arg1);

        /**
         * {@return the object constructed with the given arguments}
         *
         * @param arguments the arguments as an ordered list
         */
        @SuppressWarnings("unchecked")
        default RESULT createFromList(List<Object> arguments) {
            return create((A) arguments.get(0), (B) arguments.get(1));
        }
    }
    /**
     * A constructor function with 3 arguments.
     */
    interface Constructor3<A, B, C, RESULT> {
        /**
         * {@return the object constructed with the given arguments}
         */
        RESULT create(A arg0, B arg1, C arg2);

        /**
         * {@return the object constructed with the given arguments}
         *
         * @param arguments the arguments as an ordered list
         */
        @SuppressWarnings("unchecked")
        default RESULT createFromList(List<Object> arguments) {
            return create((A) arguments.get(0), (B) arguments.get(1), (C) arguments.get(2));
        }
    }
    /**
     * A constructor function with 4 arguments.
     */
    interface Constructor4<A, B, C, D, RESULT> {
        /**
         * {@return the object constructed with the given arguments}
         */
        RESULT create(A arg0, B arg1, C arg2, D arg3);

        /**
         * {@return the object constructed with the given arguments}
         *
         * @param arguments the arguments as an ordered list
         */
        @SuppressWarnings("unchecked")
        default RESULT createFromList(List<Object> arguments) {
            return create((A) arguments.get(0), (B) arguments.get(1), (C) arguments.get(2), (D) arguments.get(3));
        }
    }
    /**
     * A constructor function with 5 arguments.
     */
    interface Constructor5<A, B, C, D, E, RESULT> {
        /**
         * {@return the object constructed with the given arguments}
         */
        RESULT create(A arg0, B arg1, C arg2, D arg3, E arg4);

        /**
         * {@return the object constructed with the given arguments}
         *
         * @param arguments the arguments as an ordered list
         */
        @SuppressWarnings("unchecked")
        default RESULT createFromList(List<Object> arguments) {
            return create((A) arguments.get(0), (B) arguments.get(1), (C) arguments.get(2), (D) arguments.get(3), (E) arguments.get(4));
        }
    }
    /**
     * A constructor function with 6 arguments.
     */
    interface Constructor6<A, B, C, D, E, F, RESULT> {
        /**
         * {@return the object constructed with the given arguments}
         */
        RESULT create(A arg0, B arg1, C arg2, D arg3, E arg4, F arg5);

        /**
         * {@return the object constructed with the given arguments}
         *
         * @param arguments the arguments as an ordered list
         */
        @SuppressWarnings("unchecked")
        default RESULT createFromList(List<Object> arguments) {
            return create((A) arguments.get(0), (B) arguments.get(1), (C) arguments.get(2), (D) arguments.get(3), (E) arguments.get(4), (F) arguments.get(5));
        }
    }
    /**
     * A constructor function with 7 arguments.
     */
    interface Constructor7<A, B, C, D, E, F, G, RESULT> {
        /**
         * {@return the object constructed with the given arguments}
         */
        RESULT create(A arg0, B arg1, C arg2, D arg3, E arg4, F arg5, G arg6);

        /**
         * {@return the object constructed with the given arguments}
         *
         * @param arguments the arguments as an ordered list
         */
        @SuppressWarnings("unchecked")
        default RESULT createFromList(List<Object> arguments) {
            return create((A) arguments.get(0), (B) arguments.get(1), (C) arguments.get(2), (D) arguments.get(3), (E) arguments.get(4), (F) arguments.get(5), (G) arguments.get(6));
        }
    }
    /**
     * A constructor function with 8 arguments.
     */
    interface Constructor8<A, B, C, D, E, F, G, H, RESULT> {
        /**
         * {@return the object constructed with the given arguments}
         */
        RESULT create(A arg0, B arg1, C arg2, D arg3, E arg4, F arg5, G arg6, H arg7);

        /**
         * {@return the object constructed with the given arguments}
         *
         * @param arguments the arguments as an ordered list
         */
        @SuppressWarnings("unchecked")
        default RESULT createFromList(List<Object> arguments) {
            return create((A) arguments.get(0), (B) arguments.get(1), (C) arguments.get(2), (D) arguments.get(3), (E) arguments.get(4), (F) arguments.get(5), (G) arguments.get(6), (H) arguments.get(7));
        }
    }
    /**
     * A constructor function with 9 arguments.
     */
    interface Constructor9<A, B, C, D, E, F, G, H, I, RESULT> {
        /**
         * {@return the object constructed with the given arguments}
         */
        RESULT create(A arg0, B arg1, C arg2, D arg3, E arg4, F arg5, G arg6, H arg7, I arg8);

        /**
         * {@return the object constructed with the given arguments}
         *
         * @param arguments the arguments as an ordered list
         */
        @SuppressWarnings("unchecked")
        default RESULT createFromList(List<Object> arguments) {
            return create((A) arguments.get(0), (B) arguments.get(1), (C) arguments.get(2), (D) arguments.get(3), (E) arguments.get(4), (F) arguments.get(5), (G) arguments.get(6), (H) arguments.get(7), (I) arguments.get(8));
        }
    }
    /**
     * A constructor function with 10 arguments.
     */
    interface Constructor10<A, B, C, D, E, F, G, H, I, J, RESULT> {
        /**
         * {@return the object constructed with the given arguments}
         */
        RESULT create(A arg0, B arg1, C arg2, D arg3, E arg4, F arg5, G arg6, H arg7, I arg8, J arg9);

        /**
         * {@return the object constructed with the given arguments}
         *
         * @param arguments the arguments as an ordered list
         */
        @SuppressWarnings("unchecked")
        default RESULT createFromList(List<Object> arguments) {
            return create((A) arguments.get(0), (B) arguments.get(1), (C) arguments.get(2), (D) arguments.get(3), (E) arguments.get(4), (F) arguments.get(5), (G) arguments.get(6), (H) arguments.get(7), (I) arguments.get(8), (J) arguments.get(9));
        }
    }
}