package net.neoforged.camelot.api.config.impl;

import net.neoforged.camelot.api.config.type.ObjectOptionBuilders;
import net.neoforged.camelot.api.config.type.OptionBuilder;
import net.neoforged.camelot.api.config.type.OptionBuilderFactory;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;

// This file is autogenerated. DO NOT MODIFY IT MANUALLY
@SuppressWarnings({"rawtypes", "unchecked"})
record ObjectOptionBuilder<G, O>(List<ObjectOption.BuilderOption<G, O, ?, ?>> options) implements OptionBuilder.CompositeStarter<G, O>, ObjectOptionBuilders.Builder1, ObjectOptionBuilders.Builder2, ObjectOptionBuilders.Builder3, ObjectOptionBuilders.Builder4, ObjectOptionBuilders.Builder5, ObjectOptionBuilders.Builder6, ObjectOptionBuilders.Builder7, ObjectOptionBuilders.Builder8, ObjectOptionBuilders.Builder9, ObjectOptionBuilders.Builder10 {
    ObjectOptionBuilder(List<ObjectOption.BuilderOption<G, O, ?, ?>> previous, ObjectOption.BuilderOption<G, O, ?, ?> extra) {
        var newOptions = new ArrayList<>(previous);
        newOptions.add(extra);
        this(newOptions);
    }

    @Override
    public ObjectOptionBuilder<G, O> field(String id, Function extractor, OptionBuilderFactory factory, Function configurator) {
        return new ObjectOptionBuilder<>(this.options, new ObjectOption.BuilderOption<>(id, extractor, factory, configurator));
    }
    
    @Override
    public ObjectOptionBuilder<G, O> field(String id, Function extractor, OptionBuilderFactory fieldFactory, String displayName, String description) {
        return field(id, extractor, fieldFactory, b -> ((OptionBuilder) b).displayName(displayName).description(description));
    }

    @Override
    public ObjectOptionBuilder<G, O> field(String id, Function extractor, OptionBuilderFactory fieldFactory, String displayName, String description, Object defaultValue) {
        return field(id, extractor, fieldFactory, b -> ((OptionBuilder) b).displayName(displayName).description(description).defaultValue(defaultValue));
    }

    @Override
    public OptionBuilderFactory construct(ObjectOptionBuilders.Constructor1 constructor) {
        return new ObjectOption.Factory(this.options, constructor::createFromList);
    }

    @Override
    public OptionBuilderFactory construct(ObjectOptionBuilders.Constructor2 constructor) {
        return new ObjectOption.Factory(this.options, constructor::createFromList);
    }

    @Override
    public OptionBuilderFactory construct(ObjectOptionBuilders.Constructor3 constructor) {
        return new ObjectOption.Factory(this.options, constructor::createFromList);
    }

    @Override
    public OptionBuilderFactory construct(ObjectOptionBuilders.Constructor4 constructor) {
        return new ObjectOption.Factory(this.options, constructor::createFromList);
    }

    @Override
    public OptionBuilderFactory construct(ObjectOptionBuilders.Constructor5 constructor) {
        return new ObjectOption.Factory(this.options, constructor::createFromList);
    }

    @Override
    public OptionBuilderFactory construct(ObjectOptionBuilders.Constructor6 constructor) {
        return new ObjectOption.Factory(this.options, constructor::createFromList);
    }

    @Override
    public OptionBuilderFactory construct(ObjectOptionBuilders.Constructor7 constructor) {
        return new ObjectOption.Factory(this.options, constructor::createFromList);
    }

    @Override
    public OptionBuilderFactory construct(ObjectOptionBuilders.Constructor8 constructor) {
        return new ObjectOption.Factory(this.options, constructor::createFromList);
    }

    @Override
    public OptionBuilderFactory construct(ObjectOptionBuilders.Constructor9 constructor) {
        return new ObjectOption.Factory(this.options, constructor::createFromList);
    }

    @Override
    public OptionBuilderFactory construct(ObjectOptionBuilders.Constructor10 constructor) {
        return new ObjectOption.Factory(this.options, constructor::createFromList);
    }

}